services:
  app:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/

  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "pustu"
      MYSQL_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "mysql:/var/lib/mysql"
      - "./db/pustu.sql:/docker-entrypoint-initdb.d/pustu.sql"
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-ppassword"
      retries: 3
      timeout: 5s

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: "mysql"
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "pustu"
      MYSQL_USER: "root"
      PMA_USER: "root"
      MYSQL_PASSWORD: "12345678"
      PMA_PASSWORD: "12345678"

volumes:
  mysql:
    driver: local
